# 前端异常监控

## 前端错误异常的捕获方式

- try-catch (ES 提供基本的错误捕获语法)

  1. 只能捕获同步代码的异常

- window.onerror = cb

  1. img
  2. script
  3. link

- window.addEventListener('error', cb, true)
- window.addEventListener("unhandledrejection", cb)
- Promise.then().catch(cb)
- 封装 XMLHttpRequest&fetch(监测请求错误异常)

## try-catch

将能引发异常的代码块放到 try 中，并对应一个响应，然后有异常会被捕获

```
   try {
   // 模拟一段可能有错误的代码
   throw new Error("会有错误的代码块")
 } catch(e){
   // 捕获到try中代码块的错误得到一个错误对象e，进行处理分析
   report(e)
 } finally {
   console.log("finally")
```

## onerror 事件

### window.onerror

当 JavaScript 运行时错误（包括语法错误）发生时，window 会触发一个 ErrorEvent 接口的事件，并执行 window.onerror();

语法错误会导致出现语法错误的那个脚本块执行失败，当前代码块运行终止，从而导致整个程序运行中断，如果语法错误这个发生在我们的错误监控语句块中，那么我们就什么也监控不到了

```
 /**
* @description 运行时错误处理器
* @param {string} message 错误信息
* @param {string} source 发生错误的脚本URL
* @param {number} lineno 发生错误的行号
* @param {number} colno 发生错误的列号
* @param {object} error Error对象
*/
window.onerror = function (message,source,lineno,colno,error) {...}
```

### element.onerror

当一项资源（如\<img>或\<script>）加载失败，加载资源的元素会触发一个 Event 接口的 error 事件，并执行该元素上的 onerror()处理函数。

```
element.onerror = function(event) { ... } //注意和window.onerror的参数不同
```

这些 error 事件不会向上冒泡到 window，不过能被单一的 window.addEventListener 捕获

### error 事件捕获资源加载错误

资源加载失败，不会冒泡，但是会被 addEventListener 捕获，所以我们可以指定在加载失败事件的捕获阶段捕获该错误

注意: 接口同时也能捕获运行时错误

```
window.addEventListener("error", function(e) {
    var eventType = [].toString.call(e, e);
    if (eventType === "[object Event]") { // 过滤掉运行时错误
      // 上报加载错误
      report(e)
    }
  },
  true
);
```

## unhandledrejection 事件捕获 Promise 异常

最新的规范中定义了 unhandledrejection 事件用于全局捕获 promise 对象没有 rejection 处理器时异常情况

```
window.addEventListener("unhandledrejection", function (event) {
    // ...your code here to handle the unhandled rejection...

    // Prevent the default handling (error in console)
    event.preventDefault();
});
```

## Promise.then().catch(cb).finally()

Promise 中的错误会被 Promise.prototype.catch 捕获，所以我们通过这种方式捕获错误，这包括一些不支持 unhandledrejection 事件的环境中 promisede polyfill 实现

```
new Promise(function(resolve, reject) {
  throw 'Uncaught Exception!';
}).catch(function(e) {
  console.log(e); // Uncaught Exception!
});
```
